language: go
sudo: false
go_import_path: go.uber.org/automaxprocs

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: "1.12.x"
    - go: "1.13.x"
      env: LINT=1

install:
  - make install

before_script:
  - go get golang.org/x/lint/golint honnef.co/go/tools/cmd/staticcheck

script:
  - test -z "$LINT" || make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
